--liquibase formatted sql
--changeset amit:1 labels:example-label context:example-context


CREATE TABLE department (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address1 VARCHAR(50),
    address2 VARCHAR(50),
    city VARCHAR(30)
)

--rollback DROP TABLE person;

--changeset amit:2 labels: table-company context: dev
--comment: example comment
create table company (
    id SERIAL PRIMARY KEY,
    name varchar(50) not NULL,
    address1 varchar(50),
    address2 varchar(50),
    city varchar(30)
)
--rollback DROP TABLE company;

--changeset amit:3 labels: table-company-update context: dev
--comment: example comment
alter table person add column country varchar(2)
--rollback ALTER TABLE person DROP COLUMN country;

