name: Liquibase Deployment via Jump Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMP_HOST_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Jump Host to known_hosts
        run: |
          ssh-keyscan -H 20.56.159.75 >> ~/.ssh/known_hosts

      - name: Deploy Liquibase Changes via Jump Host
        run: |
          ssh -i ~/.ssh/id_rsa pgadmin@20.56.159.75 << 'EOF'
            set -e
            sudo su - root
            cd /root/Liquibase

            # Check for unstaged changes
            if ! git diff --quiet || ! git diff --cached --quiet; then
              echo "Unstaged changes detected. Stashing changes before pull."
              git stash
              git pull origin main --rebase
              git stash pop
            else
              git pull origin main --rebase
            fi

            # Ensure Maven is installed
            if ! command -v mvn &> /dev/null; then
              echo "Maven not found. Installing Maven."
              apt-get update
              apt-get install -y maven
            fi

            # Run Liquibase update
            mvn liquibase:update
          EOF
