name: Liquibase Deploy

on:
  workflow_dispatch:


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: |
          # Use the workspace directory where the repo is cloned
          cd ${GITHUB_WORKSPACE}
          mvn test
      - name: Build with Maven
        run: |
          # Use the workspace directory where the repo is cloned
          cd ${GITHUB_WORKSPACE}
          mvn clean package -DskipTests
  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMP_HOST_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Add Jump Host to known_hosts
        run: |
          ssh-keyscan -H 98.71.128.218 >> ~/.ssh/known_hosts
      - name: Deploy Liquibase Changes via Jump Host
        run: |
          ssh -i ~/.ssh/id_rsa pgadmin@98.71.128.218 << 'EOF'
            set -e
            sudo su - root
            # Clone or update repository
            if [ ! -d "/mnt/Liquibase" ]; then
              echo "Cloning repository..."
              git clone https://github.com/amit-pal-maersk/Liquibase.git /mnt/Liquibase
            else
              echo "Repository exists. Pulling latest changes..."
              cd /mnt/Liquibase
              git pull origin main --rebase
            fi
            # Ensure Maven is installed
            if ! command -v mvn &> /dev/null; then
              echo "Maven not found. Installing Maven..."
              yum update -y
              yum install -y maven
            fi
            # Run Liquibase update (relies on liquibase.properties)
            cd /mnt/Liquibase
            mvn liquibase:update
            
            echo "Liquibase deployment completed successfully"
          EOF
