name: Liquibase CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package -DskipTests

  cd:
    needs: ci
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Liquibase changes via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: pgadmin
          key: ${{ secrets.JUMP_HOST_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            sudo su - root

            REPO_DIR='/mnt/Liquibase'
            if [ ! -d "${REPO_DIR}" ]; then
              git clone https://github.com/amit-pal-maersk/Liquibase.git "${REPO_DIR}"
            else
              cd "${REPO_DIR}"
              git pull origin main --rebase
            fi

            if ! command -v mvn &> /dev/null; then
              yum update -y
              yum install -y maven
            fi

            cd "${REPO_DIR}"
            mvn liquibase:update
            echo "Liquibase deployment completed successfully"
