name: Liquibase Deployment via Jump Host

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Liquibase command to run'
        required: true
        type: choice
        default: update
        options:
          - update
          - rollback
          - updateToTag
          - history
          - clearCheckSums
      tag:
        description: 'Tag for rollback/updateToTag (optional)'
        required: false
        type: string
        default: 'v1.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMP_HOST_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Jump Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.JUMP_HOST }} >> ~/.ssh/known_hosts

      - name: Run Liquibase via Jump Host
        run: |
          ssh -i ~/.ssh/id_rsa pgadmin@${{ secrets.JUMP_HOST }} << 'EOF'
            set -e
            cd /mnt/Liquibase

            case "${{ github.event.inputs.operation }}" in
              update)
                echo ":: Running liquibase:update"
                mvn liquibase:update
                ;;
              rollback)
                echo ":: Running liquibase:rollback to tag ${{ github.event.inputs.tag }}"
                mvn liquibase:rollback -Dliquibase.rollbackTag=${{ github.event.inputs.tag }}
                ;;
              updateToTag)
                echo ":: Running liquibase:update-to-tag to ${{ github.event.inputs.tag }}"
                mvn liquibase:update-to-tag -Dliquibase.updateToTag=${{ github.event.inputs.tag }}
                ;;
              history)
                echo ":: Running liquibase:history"
                mvn liquibase:history
                ;;
              clearCheckSums)
                echo ":: Running liquibase:clearCheckSums"
                mvn liquibase:clearCheckSums
                ;;
              *)
                echo ":: Error: Unknown operation '${{ github.event.inputs.operation }}'"
                exit 1
                ;;
            esac
          EOF
